package com.dzn.mall.mapper.ums;

import com.dzn.mall.model.UmsRoleResourceRelation;
import com.dzn.mall.model.UmsRoleResourceRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRoleResourceRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    long countByExample(UmsRoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int deleteByExample(UmsRoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int insert(UmsRoleResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int insertSelective(UmsRoleResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    List<UmsRoleResourceRelation> selectByExample(UmsRoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    UmsRoleResourceRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UmsRoleResourceRelation record, @Param("example") UmsRoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UmsRoleResourceRelation record, @Param("example") UmsRoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UmsRoleResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_resource_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UmsRoleResourceRelation record);
}